const { test , expect} = require("@playwright/test");

test('test automation register and place order', async ({ page }) => {
    await page.goto('https://automationexercise.com/');
    await expect(page.getByRole('heading', { name: 'AutomationExercise' }).locator('span')).toBeVisible();
    await page.getByRole('link', { name: ' Signup / Login' }).click();
    await page.getByRole('textbox', { name: 'Name' }).click();
    await page.getByRole('textbox', { name: 'Name' }).fill('divya');
    await page.getByRole('textbox', { name: 'Name' }).press('Tab');
    await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').fill('divya_123@gmail.com');
    await page.getByRole('button', { name: 'Signup' }).click();
    await page.getByRole('radio', { name: 'Mr.' }).check();
    await page.getByRole('textbox', { name: 'Password *' }).click();
    await page.getByRole('textbox', { name: 'Password *' }).fill('abcd');
    await page.locator('#days').selectOption('5');
    await page.locator('#months').selectOption('7');
    await page.locator('#years').selectOption('2007');
    await page.getByRole('textbox', { name: 'First name *' }).click();
    await page.getByRole('textbox', { name: 'First name *' }).fill('divya');
    await page.getByRole('textbox', { name: 'Last name *' }).click();
    await page.getByRole('textbox', { name: 'Last name *' }).fill('c');
    await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).click();
    await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).fill('ddk road');
    await page.getByRole('textbox', { name: 'State *' }).click();
    await page.getByRole('textbox', { name: 'State *' }).fill('karnataka');
    await page.getByRole('textbox', { name: 'City * Zipcode *' }).click();
    await page.getByRole('textbox', { name: 'City * Zipcode *' }).fill('benhaluru');
    await page.locator('#zipcode').click();
    await page.locator('#zipcode').fill('560008');
    await page.getByRole('textbox', { name: 'Mobile Number *' }).click();
    await page.getByRole('textbox', { name: 'Mobile Number *' }).fill('78654325');
    await page.getByRole('button', { name: 'Create Account' }).click();
    await page.getByRole('link', { name: 'Continue' }).click();
    await page.locator('.choose > .nav > li > a').first().click();
    await page.getByRole('button', { name: ' Add to cart' }).click();
    await page.getByRole('button', { name: 'Continue Shopping' }).click();
    await page.getByRole('link', { name: ' Cart' }).click();
    await expect(page.getByRole('link', { name: 'Blue Top' })).toBeVisible();
    await page.getByText('Proceed To Checkout').click();
    await expect(page.locator('#address_delivery').getByText('Mr. divya c')).toBeVisible();
    await expect(page.locator('#address_invoice').getByText('ddk road')).toBeVisible();
    await expect(page.getByRole('row', { name: 'Total Amount Rs.' }).getByRole('paragraph')).toBeVisible();
    await page.locator('textarea[name="message"]').click();
    await page.locator('textarea[name="message"]').fill('Thank you');
    await page.getByRole('link', { name: 'Place Order' }).click();
    await page.locator('input[name="name_on_card"]').click();
    await page.locator('input[name="name_on_card"]').fill('987654321457');
    await page.locator('input[name="card_number"]').click();
    await page.locator('input[name="name_on_card"]').click();
    await page.locator('input[name="name_on_card"]').fill('ddddd');
    await page.locator('input[name="card_number"]').click();
    await page.locator('input[name="card_number"]').fill('987665454325');
    await page.getByRole('textbox', { name: 'ex.' }).click();
    await page.getByRole('textbox', { name: 'ex.' }).fill('123');
    await page.getByRole('textbox', { name: 'MM' }).click();
    await page.getByRole('textbox', { name: 'MM' }).fill('12');
    await page.getByRole('textbox', { name: 'YYYY' }).click();
    await page.getByRole('textbox', { name: 'YYYY' }).fill('2028');
    await page.getByRole('button', { name: 'Pay and Confirm Order' }).click();
    await page.getByRole('link', { name: 'Continue' }).click();
    await expect(page.getByRole('heading', { name: 'AutomationExercise' }).locator('span')).toBeVisible();
    await page.getByRole('link', { name: ' Delete Account' }).click();
    await expect(page.getByText('Account Deleted!')).toBeVisible();
    await page.getByRole('link', { name: 'Continue' }).click();
    await expect(page.getByRole('heading', { name: 'AutomationExercise' }).locator('span')).toBeVisible();
});
